### ISSUE TITLE
If run on PR events, add comment about what we do

### ISSUE THREAD

**Issue by pbrisbin** [freckle/mergeabot-action#5]
There seems to be no way to prevent the usual `CODEOWNERS`-based review-request for Dependabot PRs. This means our team is getting flagged on Dependabot PRs and aren't sure if they're supposed to review them. In a project with mergeabot, they should not. However, not all projects have mergeabot and it's not visible when you are tasked with any given PR.

I think an elegant fix would be for mergeabot, if run on a `pull_request` event, to add a comment on the PR, something to the effect of:

> This project uses mergeabot[link] and this PR will be automatically merged after [quarantine-days]. No review or action is required on your part.

We could also customize the message via `inputs`.

**Comment by stackptr** [comment]
Could even use `gh` to remove reviewers from the PR: https://cli.github.com/manual/gh_pr_edit

**Comment by pbrisbin** [comment]
I just had that thought today! I held off because I wasn't 100% there wouldn't be any ill-effects.

**Comment by pbrisbin** [comment]
No that, `gh pr edit --remove-reviewer <login>` seems to require you know who to remove. So that would be a possibly N-step operation. However, [`gh api -X DELETE /.../requested_reviewers`](https://docs.github.com/en/rest/pulls/review-requests?apiVersion=2022-11-28#remove-requested-reviewers-from-a-pull-request) seems to be able to remove them all without knowing who they are, which is what we'd want.

The only concrete hiccup I thought of was that we run this action on our own real PRs, pretending to be Dependabot, as a form of testing. We don't want to remove reviewers in that case. But a simple option to disable it in those cases should be fine.

**Comment by pbrisbin** [comment]
https://github.com/freckle/mergeabot-action/pull/8
